<!--begin::Step 4-->
<div data-kt-stepper-element="content">
    <div class="w-100">
        <!--begin::Input group-->

        <!--end::Input group-->
        <!--begin::Input group-->
        <div class="row">

            <div class="d-flex flex-column mb-7 fv-row">
                <!--begin::Label-->
                <label class="required fs-6 fw-bold form-label mb-2">How much is vehicle (&#8358;)</label>
                <!--end::Label-->
                <!--begin::Input wrapper-->
                <div class="position-relative">
                    <!--begin::Input-->
                    <input type="text"  @keypress="isNumber($event)" ref="vehichle_price" class="form-control form-control-solid" placeholder="Price of Vehicle" required />
                    <!--end::Input-->
                    <!--begin::Card logos-->

                    <!--end::Card logos-->
                </div>

            </div>




        </div>

        <div class="row">

            <div class="d-flex flex-column mb-7 fv-row">
                <!--begin::Label-->
                <label class="required fs-6 fw-bold form-label mb-2">Vehicle License Number</label>
                <!--end::Label-->
                <!--begin::Input wrapper-->
                <div class="position-relative">
                    <!--begin::Input-->
                    <input type="text" ref="vNumber" class="form-control form-control-solid" placeholder="Vehicle License Number" required />
                    <!--end::Input-->

                </div>

            </div>




        </div>

        <!--end::Input group-->
        <br>

        <div class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Upload Vehicle License</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <div class="position-relative">
                        <!--begin::Input-->
                        <input type="file" ref="cLicense" @change="onCFileChangeL" class="form-control form-control-solid" id='file' name="file" placeholder="Upload License" required />
                        <!--end::Input-->
                        <!--begin::Card logos-->

                        <!--end::Card logos-->
                    </div>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">
                        <img alt="img" v-if="clic" :src="clic" class="rounded w-100px" />
                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Proof of Ownership</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <div class="position-relative">
                        <!--begin::Input-->
                        <input type="file" ref="cProofOwner" @change="onCFileChangeP" class="form-control form-control-solid" id='file' name="file" placeholder="Upload Proof Of ownership" required />
                        <!--end::Input-->
                        <!--begin::Card logos-->

                        <!--end::Card logos-->
                    </div>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">
                        <img alt="img" v-if="cProof" :src="cProof" class="rounded w-100px" />
                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Means Of ID</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <div class="position-relative">
                        <!--begin::Input-->
                        <input type="file" ref="cMeansOfId" @change="onCFileChangeM" class="form-control form-control-solid" id='file' name="file" placeholder="Upload License" required />
                        <!--end::Input-->
                        <!--begin::Card logos-->

                        <!--end::Card logos-->
                    </div>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">
                        <img alt="img" v-if="cMeans" :src="cMeans" class="rounded w-100px" />
                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>

        <!--end::Input group-->
        <br>
        <hr>
        <h4>Upload Vehicle Image</h4>
        <br>

        <div class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Front Image</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <div class="position-relative">
                        <!--begin::Input-->
                        <input type="file" ref="vFrontImage" @change="onCFileChangeFI" class="form-control form-control-solid" id='file' name="file" placeholder="Upload License" required />
                        <!--end::Input-->
                        <!--begin::Card logos-->

                        <!--end::Card logos-->
                    </div>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">
                        <img alt="img" v-if="frontimage" :src="frontimage" class="rounded w-100px" />
                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>

        <!--end::Input group-->
        <br>

        <div class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Back View</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <div class="position-relative">
                        <!--begin::Input-->
                        <input type="file" ref="rBackView" @change="onCFileChangeBV" class="form-control form-control-solid" id='file' name="file" placeholder="Upload License" required />
                        <!--end::Input-->
                        <!--begin::Card logos-->

                        <!--end::Card logos-->
                    </div>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">
                        <img alt="img" v-if="backview" :src="backview" class="rounded w-100px" />
                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>

        <!--end::Input group-->
        <br>

        <div class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Interior</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <div class="position-relative">
                        <!--begin::Input-->
                        <input type="file" ref="rInterior" @change="onCFileChangeINT" class="form-control form-control-solid" id='file' name="file" placeholder="Upload License" required />
                        <!--end::Input-->
                        <!--begin::Card logos-->

                        <!--end::Card logos-->
                    </div>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">
                        <img alt="img" v-if="interior" :src="interior" class="rounded w-100px" />
                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>

        <!--end::Input group-->
        <br>

        <div class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Dashboard View</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <div class="position-relative">
                        <!--begin::Input-->
                        <input type="file" ref="cDash" @change="onCFileChangeDASH" class="form-control form-control-solid" id='file' name="file" placeholder="Upload License" required />
                        <!--end::Input-->
                        <!--begin::Card logos-->

                        <!--end::Card logos-->
                    </div>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">
                        <img alt="img" v-if="dashboard" :src="dashboard" class="rounded w-100px" />
                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>

        <!--end::Input group-->
        <br>




        <!--begin::Input group-->

        <!--end::Input group-->
    </div>
</div>

<div class="d-flex flex-stack pt-10">
    <!--begin::Wrapper-->

    <!--end::Wrapper-->
    <!--begin::Wrapper-->
    <div>

        <div v-if="isProcessingCom">
            <button :disabled="isProcessingCom" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">...processing
                <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
                <span class="svg-icon svg-icon-3 ms-1 me-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                        <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
                    </svg>
                </span>
                <!--end::Svg Icon--></button>

        </div>
        <div v-else>
            <button @click="sendcomprehensive()" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">Continue
                <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
                <span class="svg-icon svg-icon-3 ms-1 me-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                        <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
                    </svg>
                </span>
                <!--end::Svg Icon--></button>
        </div>

    </div>
    <!--end::Wrapper-->
</div>