<div class="row mb-7">
    <!--begin::Label-->
    <label class="col-lg-4 fw-bold text-muted">User Email</label>
    <!--end::Label-->
    <!--begin::Col-->
    <div class="col-lg-8">
        <input type="text" ref="vEmail" class="form-control form-control-solid" id='lEmail' name="lEmail" placeholder="Email Address" required />
    </div>
    <!--end::Col-->
</div>
<div class="row mb-7">
    <button v-if="!isSubmitEmailStatus" @click="emailStatus()" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">Login
        <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
        <span class="svg-icon svg-icon-3 ms-1 me-0">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
            </svg>
        </span>
        <!--end::Svg Icon--></button>
    <div v-else>
        <i class="fas fa-spinner fs-3x"></i>
    </div>
    <br>
</div>

<div class="notice d-flex bg-light-warning rounded border-warning border border-dashed p-6">
    <!--begin::Icon-->
    <!--begin::Svg Icon | path: icons/duotune/general/gen044.svg-->
    <span class="svg-icon svg-icon-2tx svg-icon-warning me-4">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
            <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="black" />
            <rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="black" />
            <rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="black" />
        </svg>
    </span>
    <!--end::Svg Icon-->
    <!--end::Icon-->
    <!--begin::Wrapper-->
    <div class="d-flex flex-stack flex-grow-1">
        <!--begin::Content-->
        <div class="fw-bold">
            <h4 class="text-gray-900 fw-bolder">Provide user Credentials</h4>
            <div class="fs-6 text-gray-700">You need to provide user credential before you can proceed below
                <!--<a class="fw-bolder" href="../dist/account/billing.html">Add Payment Method</a>. -->
            </div>
        </div>
        <!--end::Content-->
    </div>
    <!--end::Wrapper-->
</div>