<div class="row mb-7">
    <!--begin::Label-->
    <label class="col-lg-4 fw-bold text-muted">Customer BVN or CAC Number</label>
    <!--end::Label-->
    <!--begin::Col-->
    <div class="col-lg-8">
        <input type="text"  ref="rBVN" class="form-control form-control-solid"  placeholder="Customer BVN" required />
    </div>
    <!--end::Col-->
</div>

<div class="row mb-7">
    <!--begin::Label-->
    <label class="col-lg-4 fw-bold text-muted">User Email</label>
    <!--end::Label-->
    <!--begin::Col-->
    <div class="col-lg-8">
        <input type="text" v-model="userREmail" ref="vREmail" class="form-control form-control-solid" id='lEmail' name="lEmail" placeholder="Email Address" required />
    </div>
    <!--end::Col-->
</div>

<div class="row mb-7">
    <!--begin::Label-->
    <label class="col-lg-4 fw-bold text-muted">Verify Email</label>
    <!--end::Label-->
    <!--begin::Col-->
    <div class="col-lg-8">
        <input type="text" ref="vvREmail" onpaste="return false;" ondrop="return false;" autocomplete="off" class="form-control form-control-solid" id='vvREmail' name="vvREmail" placeholder="Verify Email" required />
    </div>
    <!--end::Col-->
</div>

<div class="row mb-7">
    <!--begin::Label-->
    <label class="col-lg-4 fw-bold text-muted">User Phone Number</label>
    <!--end::Label-->
    <!--begin::Col-->
    <div class="col-lg-8">
        <input type="text" ref="vRPhone" class="form-control form-control-solid" id='vRPhone' name="vRPhone" placeholder="08012121212" required />
    </div>
    <!--end::Col-->
</div>
<div class="row mb-7">
    <!--begin::Label-->
    <label class="col-lg-4 fw-bold text-muted">User Full Name <i class="fas fa-exclamation-circle ms-1 fs-7" data-bs-toggle="tooltip" title="This must be your legal name as it would be used as reference in all certificate issued"></i></label>
    <!--end::Label-->
    <!--begin::Col-->
    <div class="col-lg-8">
        <input type="text" ref="vRFullName" class="form-control form-control-solid" id='vRFullName' name="vRFullName" placeholder="Segun Chukwu Hasan" required />
    </div>
    <!--end::Col-->
</div>
<div class="row mb-7">

    <label class="form-check form-switch form-check-custom form-check-solid">

        <input class="form-check-input" type="checkbox" value="1" checked="checked" />
        <span class="form-check-label fw-bold text-muted">Accept Terms and Conditions </span>


    </label>

</div>
<div class="row mb-7">

    <label class="form-check form-switch form-check-custom form-check-solid">
        <input class="form-check-input" type="checkbox" value="1" checked="checked" />

        <span class="form-check-label fw-bold text-muted">Subscribe to Mailing List</span>


    </label>

    <!--end::Col-->
</div>
<div class="row mb-7">
    <button v-if="!isSubmitRegister" @click="registerUser()" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">Register
        <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
        <span class="svg-icon svg-icon-3 ms-1 me-0">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
            </svg>
        </span>
        <!--end::Svg Icon--></button>
    <div v-else>
        <i class="fas fa-spinner fs-3x"></i>
    </div>
    <br>
</div>