<!--begin::Step 4-->
<div data-kt-stepper-element="content">
    <div class="w-100">
        <!--begin::Input group-->

        <!--end::Input group-->
        <!--begin::Input group-->
        <div class="d-flex flex-column mb-7 fv-row">
            <!--begin::Label-->
            <label class="required fs-6 fw-bold form-label mb-2">Departure Date</label>
            <!--end::Label-->
            <!--begin::Input wrapper-->
            <div class="position-relative">
                <!--begin::Input-->
                <input type="date" class="form-control form-control-solid" id='tlicense' name="tlicense" placeholder="Upload License" required />
                <!--end::Input-->
                <!--begin::Card logos-->

                <!--end::Card logos-->
            </div>

            <!--begin::Item-->
            <div class="overlay me-10">
                <!--begin::Image-->
                <div class="overlay-wrapper">
                    <img alt="img" v-if="lic" :src="lic" class="rounded w-100px" />
                </div>
                <!--end::Image-->

            </div>


            <!--end::Input wrapper-->
        </div>
        <!--end::Input group-->
        <br>

        <div class="d-flex flex-column mb-7 fv-row">
            <!--begin::Label-->
            <label class="required fs-6 fw-bold form-label mb-2">Upload Proof of ownership</label>
            <!--end::Label-->
            <!--begin::Input wrapper-->
            <div class="position-relative">
                <!--begin::Input-->
                <input type="file" ref="ownership" accept="image/*, application/pdf" @change="onFileChangeO" class="form-control form-control-solid" id='file' name="file" placeholder="Upload Owner Proof" required />
                <!--end::Input-->
                <!--begin::Card logos-->

                <!--end::Card logos-->
            </div>

            <div class="overlay me-10">
                <!--begin::Image-->
                <div class="overlay-wrapper">
                    <img alt="img" v-if="own" :src="own" class="rounded w-100px" />
                </div>
                <!--end::Image-->

            </div>

            <!--end::Input wrapper-->
        </div>
        <!--begin::Input group-->
        <div class="d-flex flex-stack">
            <!--begin::Label-->
            <div class="me-5">
                <label class="fs-6 fw-bold form-label">Save Card for further billing?</label>
                <div class="fs-7 fw-bold text-muted">If you need more info, please check budget planning</div>
            </div>
            <!--end::Label-->
            <!--begin::Switch-->
            <label class="form-check form-switch form-check-custom form-check-solid">
                <input class="form-check-input" type="checkbox" value="1" checked="checked" />
                <span class="form-check-label fw-bold text-muted">Save Card</span>
            </label>
            <!--end::Switch-->
        </div>
        <!--end::Input group-->
    </div>
</div>
<!--end::Step 4-->
<!--begin::Step 5-->

<!--end::Step 5-->
<!--begin::Actions-->
<div class="d-flex flex-stack pt-10">
    <!--begin::Wrapper-->

    <!--end::Wrapper-->
    <!--begin::Wrapper-->
    <div>

        <div v-if="isProcessingThird">
            <button :disabled="isProcessingThird" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">...processing
                <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
                <span class="svg-icon svg-icon-3 ms-1 me-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                        <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
                    </svg>
                </span>
                <!--end::Svg Icon--></button>

        </div>
        <div v-else>
            <button @click="sendthrirdparty()" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">Continue
                <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
                <span class="svg-icon svg-icon-3 ms-1 me-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                        <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
                    </svg>
                </span>
                <!--end::Svg Icon--></button>
        </div>
    </div>
    <!--end::Wrapper-->
</div>