<!--begin::Step 4-->
<div data-kt-stepper-element="content">
    <div class="w-100">
        <!--begin::Input group-->

        <div v-if="motorCategory.length" class="row">
            <div class="col-xl-6 col-xs-12">
                <div class="d-flex flex-column mb-7 fv-row">
                    <!--begin::Label-->
                    <label class="required fs-6 fw-bold form-label mb-2">Motor Category</label>
                    <!--end::Label-->
                    <!--begin::Input wrapper-->
                    <select class="form-select form-select-solid" data-control="select2" data-hide-search="true" @change="changeCategory($event)" data-placeholder="Select a Motor category">
                        <option value="0">Select Category</option>
                        <option v-for="nat  in motorCategory" :value="nat.id">{{nat.category}}

                        </option>


                    </select>

                </div>

            </div>

            <div class="col-xl-6 col-xs-12">
                <div class="overlay me-10">
                    <!--begin::Image-->
                    <div class="overlay-wrapper">


                        <div class="col-xxl-12">

                            <!--begin::Title-->

                            <!--end::Title-->
                            <!--begin::Accordion-->
                            <!--begin::Section-->
                            <div class="m-0">
                                <!--begin::Heading-->
                                <div class="d-flex align-items-center collapsible py-3 toggle mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_1">
                                    <!--begin::Icon-->
                                    <div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
                                        <!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
                                        <span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
                                                <rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->
                                        <!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
                                        <span class="svg-icon toggle-off svg-icon-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
                                                <rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
                                                <rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->
                                    </div>
                                    <!--end::Icon-->
                                    <!--begin::Title-->
                                    <h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">{{categoryType}}</h4>
                                    <!--end::Title-->
                                </div>
                                <!--end::Heading-->
                                <!--begin::Body-->
                                <div id="kt_job_4_1" class="collapse fs-6 ms-1">
                                    <!--begin::Text-->
                                    <div class="col-xs-12">
                                        <img :src="categoryImage" class="rounded w-200px" />
                                        <br>
                                        <div class="mb-4 text-gray-600 fw-bold fs-6 ps-10" v-html="categoryMessage"></div>

                                        <!--end::Text-->
                                    </div>
                                </div>
                                <!--end::Content-->
                                <!--begin::Separator-->
                                <div class="separator separator-dashed"></div>
                                <!--end::Separator-->
                            </div>
                            <!--end::Section-->
                            <!--begin::Section-->

                            <!--end::Section-->
                            <!--begin::Section-->

                            <!--end::Section-->
                            <!--begin::Section-->

                            <!--end::Section-->
                            <!--end::Accordion-->
                        </div>




                    </div>
                    <!--end::Image-->

                </div>

            </div>
        </div>






        <div class="d-flex flex-column mb-7 fv-row">
            <!--begin::Label-->
            <label class="required fs-6 fw-bold form-label mb-2">Vehicle Reg. Number</label>
            <!--end::Label-->
            <!--begin::Input wrapper-->
            <div class="position-relative">
                <!--begin::Input-->
                <input type="text" v-model="vNumber" class="form-control form-control-solid" required />
                <!--end::Input-->
                <!--begin::Card logos-->

                <!--end::Card logos-->
            </div>

        </div>

        <!--end::Input group-->
        <!--begin::Input group-->
        <div class="d-flex flex-column mb-7 fv-row">
            <!--begin::Label-->
            <label class="required fs-6 fw-bold form-label mb-2">Upload Vehicle License</label>
            <!--end::Label-->
            <!--begin::Input wrapper-->
            <div class="position-relative">
                <!--begin::Input-->
                <input type="file" ref="tlicense" accept="image/*, application/pdf" @change="onFileChangeL" class="form-control form-control-solid" id='tlicense' name="tlicense" placeholder="Upload License" required />
                <!--end::Input-->
                <!--begin::Card logos-->

                <!--end::Card logos-->
            </div>

            <!--begin::Item-->
            <div class="overlay me-10">
                <!--begin::Image-->
                <div class="overlay-wrapper">
                    <img alt="img" v-if="lic" :src="lic" class="rounded w-100px" />
                </div>
                <!--end::Image-->

            </div>


            <!--end::Input wrapper-->
        </div>
        <!--end::Input group-->
        <br>

        <div class="d-flex flex-column mb-7 fv-row">
            <!--begin::Label-->
            <label class="required fs-6 fw-bold form-label mb-2">Upload Proof of ownership</label>
            <!--end::Label-->
            <!--begin::Input wrapper-->
            <div class="position-relative">
                <!--begin::Input-->
                <input type="file" ref="ownership" accept="image/*, application/pdf" @change="onFileChangeO" class="form-control form-control-solid" id='file' name="file" placeholder="Upload Owner Proof" required />
                <!--end::Input-->
                <!--begin::Card logos-->

                <!--end::Card logos-->
            </div>

            <div class="overlay me-10">
                <!--begin::Image-->
                <div class="overlay-wrapper">
                    <img alt="img" v-if="own" :src="own" class="rounded w-100px" />
                </div>
                <!--end::Image-->

            </div>

            <!--end::Input wrapper-->
        </div>
        <!--begin::Input group-->

        <!--end::Input group-->
    </div>
</div>
<!--end::Step 4-->
<!--begin::Step 5-->

<!--end::Step 5-->
<!--begin::Actions-->
<div class="d-flex flex-stack pt-10">
    <!--begin::Wrapper-->

    <!--end::Wrapper-->
    <!--begin::Wrapper-->
    <div>

        <div v-if="isProcessingThird">
            <button :disabled="isProcessingThird" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">...processing
                <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
                <span class="svg-icon svg-icon-3 ms-1 me-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                        <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
                    </svg>
                </span>
                <!--end::Svg Icon--></button>

        </div>
        <div v-else>
            <button @click="sendthrirdparty()" type="button" class="btn btn-lg block btn-primary" data-kt-stepper-action="next">Continue
                <!--begin::Svg Icon | path: icons/duotune/arrows/arr064.svg-->
                <span class="svg-icon svg-icon-3 ms-1 me-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="18" y="13" width="13" height="2" rx="1" transform="rotate(-180 18 13)" fill="black" />
                        <path d="M15.4343 12.5657L11.25 16.75C10.8358 17.1642 10.8358 17.8358 11.25 18.25C11.6642 18.6642 12.3358 18.6642 12.75 18.25L18.2929 12.7071C18.6834 12.3166 18.6834 11.6834 18.2929 11.2929L12.75 5.75C12.3358 5.33579 11.6642 5.33579 11.25 5.75C10.8358 6.16421 10.8358 6.83579 11.25 7.25L15.4343 11.4343C15.7467 11.7467 15.7467 12.2533 15.4343 12.5657Z" fill="black" />
                    </svg>
                </span>
                <!--end::Svg Icon--></button>
        </div>
    </div>
    <!--end::Wrapper-->
</div>