<div id="vTopMenu" class="header-menu align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="header-menu" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_header_menu_mobile_toggle" data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_body', lg: '#kt_header_nav'}">
    <!--begin::Menu-->
    <div class="menu menu-lg-rounded menu-column menu-lg-row menu-state-bg menu-title-gray-700 menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-400 fw-bold my-5 my-lg-0 align-items-stretch" id="#kt_header_menu" data-kt-menu="true">
        <div class="menu-item  me-lg-1">
            <span class="menu-link py-3">
                <a class="menu-link py-3" href="<?= $this->url("home") ?>">
                    <span class="menu-title">Dashboard</span>
                    <span class="menu-arrow d-lg-none"></span>
                </a>
            </span>

        </div>
        <div v-if="sessionDetails != null" data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion me-lg-1">
            <span class="menu-link py-3">
                <span class="menu-title">Account</span>
                <span class="menu-arrow d-lg-none"></span>
            </span>
            <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-lg-225px">
                <div class="menu-item">
                    <a class="menu-link py-3" href="<?= $this->url("application", ["action" => "profile"]) ?>">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">My Profle</span>
                    </a>
                </div>
                <div class="menu-item">
                    <a class="menu-link py-3" href="">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">Contact Admin</span>
                    </a>
                </div>



            </div>
        </div>
        <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion me-lg-1">
            <span class="menu-link py-3">
                <span class="menu-title">Motor</span>
                <span class="menu-arrow d-lg-none"></span>
            </span>
            <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-lg-225px">
                <div class="menu-item">
                    <a class="menu-link py-3" href="<?= $this->url("application", ["action" => "motor"]) ?>">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">New</span>
                    </a>
                </div>
                <div v-if="sessionDetails != null" class="menu-item">
                    <a class="menu-link py-3" href="<?= $this->url() ?>" data-kt-page="pro">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">View All
                            <span class="badge badge-pro badge-light-danger fw-bold fs-9 px-2 py-1 ms-1">Pro</span></span>
                    </a>
                </div>



            </div>
        </div>
        <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion me-lg-1">
            <span class="menu-link py-3">
                <span class="menu-title">Travel</span>
                <span class="menu-arrow d-lg-none"></span>
            </span>
            <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-lg-225px">
                <div class="menu-item">
                    <a class="menu-link py-3" href="<?= $this->url("application", ["action" => "travel-insurance"]) ?>">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">New</span>
                    </a>
                </div>
                <div v-if="sessionDetails != null" class="menu-item">
                    <a class="menu-link py-3" href="<?= $this->url("travel", ["action" => "view-all"]) ?>">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">View All
                        </span>
                    </a>
                </div>



            </div>
        </div>

        <div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion me-lg-1">
            <span class="menu-link py-3">
                <span class="menu-title">Marine Cargo</span>
                <span class="menu-arrow d-lg-none"></span>
            </span>
            <div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-lg-225px">
                <div class="menu-item">
                    <a class="menu-link py-3" href="<?= $this->url("application", ["action" => "motor"]) ?>">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">New</span>
                    </a>
                </div>
                <div v-if="sessionDetails != null" class="menu-item">
                    <a class="menu-link py-3" href="<?= $this->url() ?>" data-kt-page="pro">
                        <span class="menu-bullet">
                            <span class="bullet bullet-dot"></span>
                        </span>
                        <span class="menu-title">View All
                        </span>
                    </a>
                </div>



            </div>
        </div>

        <div v-if="sessionDetails != null" class="menu-item  me-lg-1">
            <span class="menu-link py-3">
                <a class="menu-link py-3" href="<?= $this->url("auth", ["action" => "logout"]) ?>">
                    <span class="menu-title">Logout</span>

                </a>
            </span>

        </div>


    </div>
    <!--end::Menu-->
</div>

<script>
    const topMenuApp = Vue.createApp({
        data() {
            return {

                sessionDetails: null,
                sessionUid: null,
                sessionDetailsStrigify: null,
            }
        },

        mounted() {
            this.getSession();
        },

        methods: {
            getSession() {
                axios.get("/auth/session").then(res => {
                    if (res.status == 200) {

                        this.sessionDetails = res.data.data;
                        this.sessionDetailsStrigify = JSON.stringify(res.data.data);
                        this.sessionUid = res.data.data.uid;
                        // console.log(this.sessionUid);
                        // return ;

                    }
                }).catch();
            },
        },

    }).mount("#vTopMenu");
</script>