<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \Application\Entity\Invoice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'invoiceUuid', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'generatedOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'amount', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'transaction', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'createdOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'updatedOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'invoiceUid', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'modifiedOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'isOpen'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'invoiceUuid', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'generatedOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'amount', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'transaction', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'createdOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'updatedOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'invoiceUid', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'modifiedOn', '' . "\0" . 'Application\\Entity\\Invoice' . "\0" . 'isOpen'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Invoice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Application\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeneratedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeneratedOn', []);

        return parent::getGeneratedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeneratedOn(\DateTime $generatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeneratedOn', [$generatedOn]);

        return parent::setGeneratedOn($generatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceUid', []);

        return parent::getInvoiceUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceUid(string $invoiceUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceUid', [$invoiceUid]);

        return parent::setInvoiceUid($invoiceUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedOn', []);

        return parent::getModifiedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedOn(\DateTime $modifiedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedOn', [$modifiedOn]);

        return parent::setModifiedOn($modifiedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn(\Datetime $createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount(string $amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOpen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOpen', []);

        return parent::getIsOpen();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOpen(bool $isOpen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOpen', [$isOpen]);

        return parent::setIsOpen($isOpen);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn(\Datetime $updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceUuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceUuid', []);

        return parent::getInvoiceUuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceUuid(string $invoiceUuid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceUuid', [$invoiceUuid]);

        return parent::setInvoiceUuid($invoiceUuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

}
