<?php
// var_dump($data[0]["user"]["fullname"]);
?>
<section class="section profile">
    <div class="row">
        <div class="col-xl-4">

            <div class="card">
                <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

                    <img src="/svg/avatar.svg" alt="Profile" class="rounded-circle">
                    <h2><?= strtoupper($data["user"]["fullname"]) ?></h2>
                    <h3><?= $data["user"]["phonenumber"] ?></h3>
                    <h3><?= $data["user"]["email"] ?></h3>
                </div>
            </div>

        </div>

        <div class="col-xl-8">

            <div class="card">
                <div class="card-body pt-3">
                    <!-- Bordered Tabs -->
                    <ul class="nav nav-tabs nav-tabs-bordered">

                        <li class="nav-item">
                            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                        </li>
                        <li class="nav-item">
                            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Invoice</button>
                        </li>
                        <?php
                        if ($data["travelList"] != NULL) :
                            if (count($data["travelList"]) > 0) : ?>

                                <li class="nav-item">
                                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings">Travelers List</button>
                                </li>
                        <?php
                            endif;
                        endif; ?>
                        <!--
                        <li class="nav-item">
                            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings">Settings</button>
                        </li>
                        -->



                    </ul>
                    <div class="tab-content pt-2">

                        <div class="tab-pane fade show active profile-overview" id="profile-overview">

                            <h5 class="card-title">Travel Insurance Details</h5>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label ">Customer Date Of Birth</div>
                                <div class="col-lg-9 col-md-8"><?= $this->dateformat($data["dob"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us"); ?></div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Travel Destination</div>
                                <div class="col-lg-9 col-md-8"> <?= $data["destination"]["name"] ?></div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Traveler Nationality </div>
                                <div class="col-lg-9 col-md-8"> <?= $data["nationality"]["name"] ?></div>
                            </div>


                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Departure Date </div>
                                <div class="col-lg-9 col-md-8"><?= $this->dateformat($data["departureDate"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us"); ?> </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Return Date </div>
                                <div class="col-lg-9 col-md-8"><?= $this->dateformat($data["returnDate"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us"); ?> </div>
                            </div>


                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Invoice Status </div>
                                <div class="col-lg-9 col-md-8"><?= $this->adminInvoiceStatus($data["invoice"]["status"]["id"]); ?> </div>
                            </div>


                        </div>
                        <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                            <!-- Profile Edit Form -->
                            <?php echo $this->partial("invoice-view-partial", ["data" => $data["invoice"]]) ?>

                        </div>

                        <?php
                        if ($data["travelList"] != NULL) :
                            if (count($data["travelList"]) > 0) : ?>
                                <div class="tab-pane fade profile-edit pt-3" id="profile-settings">

                                    List all Travelers list

                                </div>
                        <?php
                            endif;
                        endif; ?>

                        <!--  <div class="tab-pane fade pt-3" id="profile-settings">

                          Settings Form 
                            <form>

                                <div class="row mb-3">
                                    <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                                    <div class="col-md-8 col-lg-9">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="changesMade" checked>
                                            <label class="form-check-label" for="changesMade">
                                                Changes made to your account
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="newProducts" checked>
                                            <label class="form-check-label" for="newProducts">
                                                Information on new products and services
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="proOffers">
                                            <label class="form-check-label" for="proOffers">
                                                Marketing and promo offers
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                                            <label class="form-check-label" for="securityNotify">
                                                Security alerts
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Save Changes</button>
                                </div>
                            </form>

                        </div>-->



                    </div><!-- End Bordered Tabs -->

                </div>
            </div>

        </div>
    </div>
</section>