<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Service\GeneralService;

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('AIB IService')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        // ->prependStylesheet($this->basePath('assets/css/corporate-ui-dashboard.css?v=1.0.0'))
        ->prependStylesheet($this->basePath('/bbmin/assets/css/style.css'))
        ->prependStylesheet($this->basePath('/bbmin/assets/vendor/simple-datatables/style.css'))
        ->prependStylesheet($this->basePath('/bbmin/assets/vendor/remixicon/remixicon.css'))
        ->prependStylesheet($this->basePath('/bbmin/assets/vendor/quill/quill.bubble.css'))
        ->prependStylesheet($this->basePath('/bbmin/assets/vendor/quill/quill.snow.css'))
        ->prependStylesheet($this->basePath('/bbmin/assets/vendor/boxicons/css/boxicons.min.css'))
        ->prependStylesheet($this->basePath('/bbmin/assets/vendor/bootstrap-icons/bootstrap-icons.css'))
        ->prependStylesheet($this->basePath('/bbmin/assets/vendor/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet("https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i")
        ->prependStylesheet("https://fonts.gstatic.com")

    ?>

    <script src="https://kit.fontawesome.com/349ee9c857.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>
    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


    <meta property="og:locale" content="en_US" />
    <meta property="og:type" content="article" />
    <link rel="apple-touch-icon" sizes="57x57" href="/img/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/img/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/img/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/img/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/img/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/img/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/img/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/img/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/img/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">
    <link rel="manifest" href="/img/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/img/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center">
                <img src="assets/img/logo.png" alt="">
                <span class="d-none d-lg-block"><?= GeneralService::COMPANY_NAME ?></span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->



        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->





                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">Settings</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">





                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="<?= $this->url("logout") ?>">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link collapsed" href="<?= $this->url("admin") ?>">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Motor</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="<?php echo $this->url("admin-motor", ["action" => "allMotor"]) ?>">
                            <i class="bi bi-circle"></i><span>View All</span>
                        </a>
                    </li>






                </ul>
            </li><!-- End Components Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-journal-text"></i><span>Travel</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="<?= $this->url("admin-travel", ["action" => "all-travel"]) ?>">
                            <i class="bi bi-circle"></i><span>View</span>
                        </a>
                    </li>

                </ul>
            </li><!-- End Forms Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-layout-text-window-reverse"></i><span>Marine Cargo</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="<?php echo $this->url("admin-motor", ["action" => "all-motor"]) ?>">
                            <i class="bi bi-circle"></i><span>View</span>
                        </a>
                    </li>

                </ul>
            </li><!-- End Tables Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-bar-chart"></i><span>Customers</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="<?php echo $this->url("admin", ["action" => "all-customers"]) ?>">
                            <i class="bi bi-circle"></i><span>View All</span>
                        </a>
                    </li>
                    <!--<li>
                        <a href="charts-apexcharts.html">
                            <i class="bi bi-circle"></i><span>New</span>
                        </a>
                    </li> -->

                </ul>
            </li><!-- End Charts Nav -->





            <li class="nav-item">
                <a class="nav-link collapsed" href="<?= $this->url("logout") ?>">
                    <i class="bi bi-person"></i>
                    <span>Logout</span>
                </a>
            </li><!-- End Profile Page Nav -->





        </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">


        <?= $this->content ?>


    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span><?= GeneralService::COMPANY_NAME ?></span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
            Designed by <a href="">I-Manager Solutions</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="/bbmin/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="/bbmin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/bbmin/assets/vendor/chart.js/chart.min.js"></script>
    <script src="/bbmin/assets/vendor/echarts/echarts.min.js"></script>
    <script src="/bbmin/assets/vendor/quill/quill.min.js"></script>
    <script src="/bbmin/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="/bbmin/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="/bbmin/assets/vendor/php-email-form/validate.js"></script>


</body>

</html>