<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="invoice-title">
                <h2>Invoice</h2>
                <h3 class="pull-right">Order <?= strtoupper($data["invoiceUid"]) ?></h3>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-6">
                    <address>
                        <strong>Billed To:</strong><br>
                        <?= $data["user"]["fullname"] ?><br>
                        <?= $data["user"]["email"] ?><br>
                        <?= $data["user"]["phonenumber"] ?><br>

                    </address>
                </div>

            </div>
            <div class="row">
                <!-- <div class="col-xs-6">
                    <address>
                        <strong>Payment Method:</strong><br>
                        Visa ending **** 4242<br>
                        jsmith@email.com
                    </address>
                </div> -->
                <div class="col-xs-6 text-right">
                    <address>
                        <strong>Order Date:</strong> :
                        <?= $this->dateformat($data["createdOn"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE) ?><br><br>
                    </address>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Order summary</strong></h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Issued On </strong></td>
                                    <td class="text-center"><strong>Description</strong></td>
                                    <td class="text-center"><strong>Status</strong></td>
                                    <td class="text-right"><strong>Amount</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- foreach ($order->lineItems as $line) or some such thing here -->
                                <tr>
                                    <td> <?= $this->dateformat($data["createdOn"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE) ?> </td>
                                    <td class="text-center"><?= $data["description"] ?></td>
                                    <td class="text-center"><?= $this->adminInvoiceStatus($data["status"]["id"]) ?></td>
                                    <td class="text-right">&#8358; <?= $data["amount"] ?></td>
                                </tr>

                                <tr>
                                    <td class="thick-line"></td>
                                    <td class="thick-line"></td>
                                    <td class="thick-line text-center"><strong>Subtotal</strong></td>
                                    <td class="thick-line text-right">&#8358; <?= $data["amount"] ?></td>
                                </tr>
                                <tr>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line text-center"><strong>Shipping</strong></td>
                                    <td class="no-line text-right">&#8358; 0</td>
                                </tr>
                                <tr>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line text-center"><strong>Total</strong></td>
                                    <td class="no-line text-right">&#8358; <?= $data["amount"] ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>