<?php
// var_dump($data[0]["user"]["fullname"]);
?>
<section class="section profile">
    <div class="row">
        <div class="col-xl-4">

            <div class="card">
                <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

                    <img src="/svg/avatar.svg" alt="Profile" class="rounded-circle">
                    <h2><?= strtoupper($data["user"]["fullname"]) ?></h2>
                    <h3><?= $data["user"]["phonenumber"] ?></h3>
                    <h3><?= $data["user"]["email"] ?></h3>
                </div>
            </div>

        </div>

        <div class="col-xl-8">

            <div class="card">
                <div class="card-body pt-3">
                    <!-- Bordered Tabs -->
                    <ul class="nav nav-tabs nav-tabs-bordered">

                        <li class="nav-item">
                            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                        </li>

                        <li class="nav-item">
                            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Invoice</button>
                        </li>

                        <li class="nav-item">
                            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings">Settings</button>
                        </li>

                        <li class="nav-item">
                            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                        </li>

                    </ul>
                    <div class="tab-content pt-2">

                        <div class="tab-pane fade show active profile-overview" id="profile-overview">
                            <h5 class="card-title">About</h5>
                            <p class="small fst-italic">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</p>

                            <h5 class="card-title">Motor Insurance Details</h5>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label ">Cover Type</div>
                                <div class="col-lg-9 col-md-8"><?= $data["coverType"]["type"] ?></div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Car Value</div>
                                <div class="col-lg-9 col-md-8">&#8358; <?= $data["valueOfCar"] ?></div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Invoice Status </div>
                                <div class="col-lg-9 col-md-8"> <?= $this->adminInvoiceStatus($data["invoice"]["status"]["id"]) ?></div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Vehichle License </div>
                                <div class="col-lg-9 col-md-8"><a target="_blank" href="<?= $data["vehicleLicense"]["docUrl"] ?>" class="btn btn-sm"> Vehicle License Image</a>
                                    <?php if ($data["vehicleLicense"]["mimeType"] == "image/png" || $data["vehicleLicense"]["mimeType"] == "image/jpeg") : ?>
                                        <div class="col-md-4">
                                            <br><br> <img height="200" src="<?= $data["vehicleLicense"]["docUrl"] ?>" alt="Profile" class="img-fluid rounded-start">
                                        </div>
                                    <?php else : ?>
                                        <a href="<?= $data["vehicleLicense"]["docUrl"] ?>" target="_blank"><i class="fa fa-download"></i></a>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Proof of Ownership</div>
                                <?php if ($data["proofOfOwnership"]["mimeType"] == "image/png" || $data["proofOfOwnership"]["mimeType"] == "image/jpeg") : ?>
                                    <br><br>
                                    <div class="col-md-4">
                                        <img src="<?= $data["proofOfOwnership"]["docUrl"] ?>" class="img-fluid rounded-start" alt="...">
                                    </div>
                                <?php else : ?>
                                    <a href="<?= $data["proofOfOwnership"]["docUrl"] ?>"><i class="fa fa-download"></i></a>
                                <?php endif; ?>

                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Means Of Identification </div>
                                <?php if ($data["meansOfId"]["mimeType"] == "image/png" || $data["meansOfId"]["mimeType"] == "image/jpeg") : ?>
                                    <br><br>
                                    <div class="col-md-4">
                                        <img src="<?= $data["meansOfId"]["docUrl"] ?>" class="img-fluid rounded-start" alt="...">
                                    </div>
                                <?php else : ?>
                                    <a href="<?= $data["meansOfId"]["docUrl"] ?>"><i class="fa fa-download"></i></a>
                                <?php endif; ?>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Address</div>
                                <div class="col-lg-9 col-md-8">A108 Adam Street, New York, NY 535022</div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Phone</div>
                                <div class="col-lg-9 col-md-8">(436) 486-3538 x29071</div>
                            </div>

                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Email</div>
                                <div class="col-lg-9 col-md-8">k.anderson@example.com</div>
                            </div>

                        </div>

                        <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                            <!-- Profile Edit Form -->
                            <?php //$this->partial("customer-invoice-partial", ["data" => $data["invoice"]]) ?>

                        </div>

                        <div class="tab-pane fade pt-3" id="profile-settings">

                            <!-- Settings Form -->
                            <form>

                                <div class="row mb-3">
                                    <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                                    <div class="col-md-8 col-lg-9">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="changesMade" checked>
                                            <label class="form-check-label" for="changesMade">
                                                Changes made to your account
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="newProducts" checked>
                                            <label class="form-check-label" for="newProducts">
                                                Information on new products and services
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="proOffers">
                                            <label class="form-check-label" for="proOffers">
                                                Marketing and promo offers
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                                            <label class="form-check-label" for="securityNotify">
                                                Security alerts
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Save Changes</button>
                                </div>
                            </form><!-- End settings Form -->

                        </div>

                        <div class="tab-pane fade pt-3" id="profile-change-password">
                            <!-- Change Password Form -->
                            <form>

                                <div class="row mb-3">
                                    <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                                    <div class="col-md-8 col-lg-9">
                                        <input name="password" type="password" class="form-control" id="currentPassword">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                                    <div class="col-md-8 col-lg-9">
                                        <input name="newpassword" type="password" class="form-control" id="newPassword">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                                    <div class="col-md-8 col-lg-9">
                                        <input name="renewpassword" type="password" class="form-control" id="renewPassword">
                                    </div>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Change Password</button>
                                </div>
                            </form><!-- End Change Password Form -->

                        </div>

                    </div><!-- End Bordered Tabs -->

                </div>
            </div>

        </div>
    </div>
</section>