<div class="card-body" id="newpasswordApp">

    <div class="pt-4 pb-2">
        <h5 class="card-title text-center pb-0 fs-4">Reset Password</h5>
        <p class="text-center small">Enter your email</p>
    </div>

    <!--<form method="POST" action="/auth-admin/newpassword/"> -->

    <div class="col-12">
        <label for="yourUsername" class="form-label">Password</label>
        <div class="input-group has-validation">
            <span class="input-group-text" id="inputGroupPrepend"><span class="fa fa-mail"></span></span>
            <input type="password" v-model="password" name="username" class="form-control" id="yourUsername" required>
            <div class="invalid-feedback">Please enter your email.</div>
        </div>
    </div>

    <div class="col-12">
        <label for="yourUsername" class="form-label">Confirm Password</label>
        <div class="input-group has-validation">
            <span class="input-group-text" id="inputGroupPrepend"><span class="fa fa-mail"></span></span>
            <input type="password" v-model="verifypassword" name="username" class="form-control" id="yourUsername" required>
            <div class="invalid-feedback">Please enter your email.</div>
        </div>
    </div>
    <br>
    <input type="hidden" ref="hidde" value="<?= $token ?>" />




    <div class="col-12">
        <div v-if="isSubmitting">
            <i class="fas fa-spinner fs-3x"></i>
        </div>
        <div v-else>
            <button @click="newpassword" class="btn btn-primary w-100" type="submit">Send Reset</button>
        </div>

    </div>
    <!--  </form> -->


</div>

<script>
    const newwpasswordApp = Vue.createApp({
        data() {
            return {
                isSubmitting: false,
                verifypassword: "",
                password: "",

            }
        },
        methods: {
            newpassword() {
                if (this.password == "" || this.verifypassword == "") {
                    Swal.fire({
                        icon: 'error',
                        title: "Empty field",
                        text: 'A required field is empty',

                    });
                } else if (this.password !== this.verifypassword) {
                    Swal.fire({
                        icon: 'error',
                        title: "Unidentical Password",
                        text: 'Please make sure passwords are identical',

                    });
                }else{
                    this.isSubmitting = true;
                    let formData = new FormData()
                    axios.post();
                }

            }
        },
    });
    newwpasswordApp.mount("#newpasswordApp");
</script>