<div class="card-body" id="adminPasswordReset">

    <div class="pt-4 pb-2">
        <h5 class="card-title text-center pb-0 fs-4">Reset Password</h5>
        <p class="text-center small">Enter your email</p>
    </div>



    <div class="col-12">
        <label for="yourUsername" class="form-label">Email</label>
        <div class="input-group has-validation">
            <span class="input-group-text" id="inputGroupPrepend"><span class="fa fa-mail"></span></span>
            <input type="text" v-model="email" name="username" class="form-control" id="yourUsername" required>
            <div class="invalid-feedback">Please enter your email.</div>
        </div>
    </div>




    <div class="col-12">
        <div v-if="isSubmitting">
            <i class="fas fa-spinner fs-3x"></i>
        </div>
        <div v-else>
            <button @click="resetRequest" class="btn btn-primary w-100" type="submit">Reset Request</button>
        </div>

    </div>



</div>

<script>
    const resetApp = Vue.createApp({
        data() {
            return {
                email: null,
                isSubmitting: false,
            }
        },
        methods: {
            resetRequest() {
                if (this.email == null || this.email == "") {
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'A required field is empty',
                        footer: '<a href="">Why do I have this issue?</a>'
                    });
                } else {
                    let formData = new FormData();
                    formData.append("email", this.email);
                    axios.post("/auth-admin/reset", formData).then(res => {
                        if (res.status = 202) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Check Email',
                                text: 'An Email has been sent to your registered Email',
                                // footer: '<a href="">Why do I have this issue?</a>'
                            });
                        }
                    }).catch();
                }
            }
        },
    });
    resetApp.mount("#adminPasswordReset")
</script>