<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/azia.css'))
        ->prependStylesheet($this->basePath('lib/flag-icon-css/css/flag-icon.min.css'))
        ->prependStylesheet($this->basePath('lib/typicons.font/typicons.css'))
        ->prependStylesheet($this->basePath('lib/ionicons/css/ionicons.min.css'))
        ->prependStylesheet($this->basePath('lib/fontawesome-free/css/all.min.css'))



    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>


    <?= $this->content ?>



    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>

</html>