	<!--begin::Main-->
	<!--begin::Root-->

	<?php

use Application\Service\GeneralService;

	$this->headMeta($description ?? GeneralService::APP_DESCRIPTION, "description");
	$this->headMeta($description ?? GeneralService::APP_KEYWORDS, "keywords");
	$flashMessenger = $this->flashMessenger()
		->setMessageOpenFormat('<div%s>
 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
	 &times;
 </button>
 <ul><li>')
		->setMessageSeparatorString('</li><li>')
		->setMessageCloseString('</li></ul></div>');

	?>
	<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
	<?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
	<?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
	<?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>

	<div class="d-flex flex-column flex-root">
		<!--begin::Page-->
		<div class="page d-flex flex-row flex-column-fluid">
			<!--begin::Wrapper-->
			<div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">
				<!--begin::Header-->

				<!--begin::Container-->
				<div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
					<!--begin::Post-->
					<div class="content flex-row-fluid" id="kt_content">
						<!--begin::About card-->
						<div id="indexApp" class="card">
							<!--begin::Body-->
							<div class="card-body p-lg-17">


								<!--begin::Section-->
								<div class="mb-16">
									<!--begin::Top-->
									<div class="text-center mb-12">
										<!--begin::Title-->
										<h3 class="fs-2hx text-dark mb-5">Choose an insurance package that is right for you</h3>
										<!--end::Title-->
										<!--begin::Text-->
										<!--<div class="fs-5 text-muted fw-bold">Our goal is to provide a complete and robust theme solution
											<br />to boost all of our customer’s project deployments
										</div> -->
										<!--end::Text-->
									</div>
									<!--end::Top-->
									<!--begin::Row-->
									<div class="row g-10">
										<!--begin::Col-->
										<div class="col-md-4">
											<!--begin::Publications post-->
											<div class="card-xl-stretch me-md-6">
												<!--begin::Overlay-->
												<a href="<?= $this->url("application", ["action" => 'motor']) ?>">
													<!--begin::Item-->
													<div class="rectangle d-flex flex-center h-200px w-300px bg-light mx-2">
														<!--begin::Content-->
														<div class="text-left">
															<!--begin::Symbol-->
															<!--begin::Svg Icon | path: icons/duotune/general/gen025.svg-->
															<span class="svg-icon svg-icon-2tx svg-icon-primary">
																<img alt="Logo" src="/svg/motor-insurance.svg" class="h-50px h-lg-70px logo-default" />
															</span>
															<!--end::Svg Icon-->
															<!--end::Symbol-->
															<!--begin::Text-->
															<div class="mt-1">
																<!--begin::Animation-->
																<div class="fs-lg-2hx fs-2x fw-bolder text-gray-800 d-flex align-items-center">
																	<!--  <div class="min-w-70px" data-kt-countup="true" data-kt-countup-value="700">0</div>+ -->
																</div>
																<!--end::Animation-->
																<!--begin::Label-->
																<span class="text-gray-600 fw-bold fs-5 lh-0">Motor/Auto insurance</span>
																<!--end::Label-->
															</div>
															<!--end::Text-->
														</div>
														<!--end::Content-->
													</div>
												</a>
												<!--end::Overlay-->
												<!--begin::Body-->
												<div class="m-0">
													<!--begin::Title
													<a href="#" class="fs-4 text-dark fw-bolder text-hover-primary text-dark lh-base">Cover for autombile</a>-->
													<!--end::Title-->
													<!--begin::Text-->
													<!--<div class="fw-bold fs-5 text-gray-600 text-dark mt-3 mb-5">We’ve been focused on making a the from also not been afraid to and step away been focused create eye</div> -->
													<!--end::Text-->
													<!--begin::Content-->

													<!--end::Content-->
												</div>
												<!--end::Body-->
											</div>
											<!--end::Publications post-->
										</div>
										<!--end::Col-->
										<!--begin::Col-->
										<div class="col-md-4">
											<!--begin::Publications post-->
											<div class="card-xl-stretch mx-md-3">
												<!--begin::Overlay-->
												<a href="<?= $this->url("application", ["action" => 'travel-insurance']) ?>">
													<!--begin::Item-->
													<div class="rectangle d-flex flex-center h-200px w-300px bg-light mx-2">
														<!--begin::Content-->
														<div class="text-left">
															<!--begin::Symbol-->
															<!--begin::Svg Icon | path: icons/duotune/general/gen025.svg-->
															<span class="svg-icon svg-icon-2tx svg-icon-primary">
																<img alt="Logo" src="/svg/travel.svg" class="h-50px h-lg-70px logo-default" />
															</span>
															<!--end::Svg Icon-->
															<!--end::Symbol-->
															<!--begin::Text-->
															<div class="mt-1">
																<!--begin::Animation-->
																<div class="fs-lg-2hx fs-2x fw-bolder text-gray-800 d-flex align-items-center">
																	<!--  <div class="min-w-70px" data-kt-countup="true" data-kt-countup-value="700">0</div>+ -->
																</div>
																<!--end::Animation-->
																<!--begin::Label-->
																<span class="text-gray-600 fw-bold fs-5 lh-0">Travel Insurance</span>
																<!--end::Label-->
															</div>
															<!--end::Text-->
														</div>
														<!--end::Content-->
													</div>
												</a>
												<!--end::Overlay-->
												<!--begin::Body-->
												<div class="m-0">
													<!--begin::Title
													<a href="#" class="fs-4 text-dark fw-bolder text-hover-primary text-dark lh-base">Cover for autombile</a>-->
													<!--end::Title-->
													<!--begin::Text-->
													<!--<div class="fw-bold fs-5 text-gray-600 text-dark mt-3 mb-5">We’ve been focused on making the from v4 to v5 but we have also not been afraid to step away been focused</div> -->
													<!--end::Text-->
													<!--begin::Content-->

													<!--end::Content-->
												</div>
												<!--end::Body-->
											</div>
											<!--end::Publications post-->
										</div>
										<!--end::Col-->
										<!--begin::Col-->
										<div class="col-md-4">
											<!--begin::Publications post-->
											<div class="card-xl-stretch ms-md-6">
												<!--begin::Overlay-->
												<a href="#" @click="OnMarineClick()">
													<!--begin::Item-->
													<div class="rectangle d-flex flex-center h-200px w-300px bg-light mx-2">
														<!--begin::Content-->
														<div class="text-left">
															<!--begin::Symbol-->
															<!--begin::Svg Icon | path: icons/duotune/general/gen025.svg-->
															<span class="svg-icon svg-icon-2tx svg-icon-primary">
																<img alt="Logo" src="/svg/marine.svg" class="h-50px h-lg-70px logo-default" />
															</span>
															<!--end::Svg Icon-->
															<!--end::Symbol-->
															<!--begin::Text-->
															<div class="mt-1">
																<!--begin::Animation-->
																<div class="fs-lg-2hx fs-2x fw-bolder text-gray-800 d-flex align-items-center">
																	<!--  <div class="min-w-70px" data-kt-countup="true" data-kt-countup-value="700">0</div>+ -->
																</div>
																<!--end::Animation-->
																<!--begin::Label-->
																<span class="text-gray-600 fw-bold fs-5 lh-0">Marine Cargo</span>
																<!--end::Label-->
															</div>
															<!--end::Text-->
														</div>
														<!--end::Content-->
													</div>
												</a>
												<!--end::Overlay-->
												<!--begin::Body-->
												<div class="m-0">
													<!--begin::Title
													<a href="#" class="fs-4 text-dark fw-bolder text-hover-primary text-dark lh-base">Bootstrap Admin - How To Started the Dashboard Tutorial</a>-->
													<!--end::Title-->
													<!--begin::Text
													<div class="fw-bold fs-5 text-gray-600 text-dark mt-3 mb-5">We’ve been focused on making the from v4 to v5 but we’ve also not been afraid to step away been focused</div>-->
													<!--end::Text-->
													<!--begin::Content-->

													<!--end::Content-->
												</div>
												<!--end::Body-->
											</div>
											<!--end::Publications post-->
										</div>
										<!--end::Col-->
									</div>
									<!--end::Row-->
								</div>
								<!--end::Section-->


								<!--begin::About  enter about here -->










								<!--end::About-->
								<!--begin::Statistics-->

								<!--end::Statistics-->

								<!--begin::Team-->

								<!--end::Team-->
								<!--begin::Card-->
								<div class="card bg-light text-center">
									<!--begin::Body-->
									<div class="card-body py-12">
										<!--begin::Icon-->
										<a href="#" class="mx-4">
											<img src="assets/media/svg/brand-logos/facebook-4.svg" class="h-30px my-2" alt="" />
										</a>
										<!--end::Icon-->
										<!--begin::Icon-->
										<a href="#" class="mx-4">
											<img src="assets/media/svg/brand-logos/instagram-2-1.svg" class="h-30px my-2" alt="" />
										</a>
										<!--end::Icon-->
										<!--begin::Icon-->
										<a href="#" class="mx-4">
											<img src="assets/media/svg/brand-logos/github.svg" class="h-30px my-2" alt="" />
										</a>
										<!--end::Icon-->
										<!--begin::Icon-->
										<a href="#" class="mx-4">
											<img src="assets/media/svg/brand-logos/behance.svg" class="h-30px my-2" alt="" />
										</a>
										<!--end::Icon-->
										<!--begin::Icon-->
										<a href="#" class="mx-4">
											<img src="assets/media/svg/brand-logos/pinterest-p.svg" class="h-30px my-2" alt="" />
										</a>
										<!--end::Icon-->
										<!--begin::Icon-->
										<a href="#" class="mx-4">
											<img src="assets/media/svg/brand-logos/twitter.svg" class="h-30px my-2" alt="" />
										</a>
										<!--end::Icon-->
										<!--begin::Icon-->
										<a href="#" class="mx-4">
											<img src="assets/media/svg/brand-logos/dribbble-icon-1.svg" class="h-30px my-2" alt="" />
										</a>
										<!--end::Icon-->
									</div>
									<!--end::Body-->
								</div>
								<!--end::Card-->
							</div>
							<!--end::Body-->
						</div>
						<!--end::About card-->
					</div>
					<!--end::Post-->
				</div>
				<!--end::Container-->
				<!--begin::Footer-->

				<!--end::Footer-->
			</div>
			<!--end::Wrapper-->
		</div>
		<!--end::Page-->
	</div>
	<!--end::Root-->
	<!--begin::Drawers-->
	<!--begin::Activities drawer-->

	<!--end::Activities drawer-->
	<!--begin::Exolore drawer toggle-->

	<!--end::Exolore drawer toggle-->
	<!--begin::Exolore drawer-->

	<!--end::Exolore drawer-->
	<!--end::Drawers-->
	<!--begin::Modals-->
	<!--begin::Modal - Invite Friends-->

	<!--end::Modal - Invite Friend-->
	<!--begin::Modal - Create App-->

	<!--end::Modal - Create App-->
	<!--begin::Modal - New Target-->

	<!--end::Modal - New Target-->
	<!--end::Modals-->
	<!--begin::Scrolltop-->
	<div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
		<!--begin::Svg Icon | path: icons/duotune/arrows/arr066.svg-->
		<span class="svg-icon">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
				<rect opacity="0.5" x="13" y="6" width="13" height="2" rx="1" transform="rotate(90 13 6)" fill="black" />
				<path d="M12.5657 8.56569L16.75 12.75C17.1642 13.1642 17.8358 13.1642 18.25 12.75C18.6642 12.3358 18.6642 11.6642 18.25 11.25L12.7071 5.70711C12.3166 5.31658 11.6834 5.31658 11.2929 5.70711L5.75 11.25C5.33579 11.6642 5.33579 12.3358 5.75 12.75C6.16421 13.1642 6.83579 13.1642 7.25 12.75L11.4343 8.56569C11.7467 8.25327 12.2533 8.25327 12.5657 8.56569Z" fill="black" />
			</svg>
		</span>
		<!--end::Svg Icon-->
	</div>
	<!--end::Scrolltop-->
	<!--end::Main-->
	<script>
		const indexApp = Vue.createApp({
			data() {
				return {
					key: ""
				}
			},
			methods: {
				OnMarineClick() {
					Swal.fire({
						icon: 'info',
						title: 'Coming Soon',
						text: 'Working on geting this ready for you',

					})
				}
			},
		});
		indexApp.mount("#indexApp")
	</script>