<?php

use Application\Service\TransactionService;

$key = $setting->getPaystackKey();
?>



<div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
    <!--begin::Post-->
    <div id="vvInvoice" class="content flex-row-fluid" id="kt_content">
        <!--begin::Invoice-->
        <div class="card">
            <!--begin::Body-->
            <div class="card-body p-lg-20">
                <!--begin::Layout-->
                <div class="d-flex flex-column flex-xl-row">
                    <!--begin::Content-->
                    <div class="flex-lg-row-fluid me-xl-18 mb-10 mb-xl-0">
                        <!--begin::Head-->
                        <div class="d-flex flex-stack mb-10 mb-lg-15">
                            <!--begin::Logo-->
                            <a href="#">
                                <img alt="Logo" class="h-75px" src="<?= $setting->getCompanyLogo() ?>" />
                            </a>
                            <!--end::Logo-->
                            <!--begin::Actions-->
                            <div v-if="hasLoadedInvoiceDets" class="my-1">

                                <!-- <a href="#" class="btn btn-sm btn-success me-2" @click="swalTest">Print</a> -->
                                <?php if ($data->getStatus()->getId() == TransactionService::INVOICE_STATUS_INITIATED || $data->getStatus()->getId() == TransactionService::INVOICE_STATUS_UNSETTLED) : ?>
                                    <button @click="makePayment()" class="btn btn-block btn-xl btn-primary" type="submit"> Pay </button>
                                <?php endif; ?>

                            </div>
                            <!--end::Actions-->
                        </div>
                        <!--end::Head-->
                        <!--begin::Wrapper-->
                        <div class="mb-0">
                            <!--begin::Label-->
                            <div class="fw-bolder fs-3 text-gray-800 mb-8">Invoice # <?= strtoupper($data->getInvoiceUid());  ?> <br>
                                <?php echo  $this->invoicestatus($data->getStatus()->getId()) ?>
                            </div>
                            <!--end::Label-->
                            <!--begin::Row-->
                            <div class="row g-5 mb-11">
                                <!--end::Col-->
                                <div class="col-sm-6">
                                    <!--end::Label-->
                                    <div class="fw-bold fs-7 text-gray-600 mb-1">Issue Date:</div>
                                    <!--end::Label-->
                                    <!--end::Col-->
                                    <div class="fw-bolder fs-6 text-gray-800"><?= $this->dateFormat($data->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us") ?></div>
                                    <!--end::Col-->
                                </div>
                                <!--end::Col-->
                                <!--end::Col-->
                                <div class="col-sm-6">
                                    <!--end::Label-->
                                    <div class="fw-bold fs-7 text-gray-600 mb-1">Due Date:</div>
                                    <!--end::Label-->
                                    <!--end::Info-->
                                    <div class="fw-bolder fs-6 text-gray-800 d-flex align-items-center flex-wrap">
                                        <span class="pe-2"><?= $this->dateFormat($data->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us") ?></span>
                                        <span class="fs-7 text-danger d-flex align-items-center">
                                            <span class="bullet bullet-dot bg-danger me-2"></span>Due in 7 days</span>
                                    </div>
                                    <!--end::Info-->
                                </div>
                                <!--end::Col-->
                            </div>
                            <!--end::Row-->
                            <!--begin::Row-->
                            <div class="row g-5 mb-12">
                                <!--end::Col-->
                                <div class="col-sm-6">
                                    <!--end::Label-->
                                    <div class="fw-bold fs-7 text-gray-600 mb-1">Issue For:</div>
                                    <!--end::Label-->
                                    <!--end::Text-->
                                    <div class="fw-bolder fs-6 text-gray-800"><?= $data->getUser()->getFullname() ?></div>
                                    <!--end::Text-->
                                    <!--end::Description-->
                                 <!--   <div class="fw-bold fs-7 text-gray-600">8692 Wild Rose Drive
                                        <br />Livonia, MI 48150 
                                    </div>-->
                                    <!--end::Description-->
                                </div>
                                <!--end::Col-->
                                <!--end::Col-->
                                <div class="col-sm-6">
                                    <!--end::Label-->
                                    <div class="fw-bold fs-7 text-gray-600 mb-1">Issued By:</div>
                                    <!--end::Label-->
                                    <!--end::Text-->
                                    <div class="fw-bolder fs-6 text-gray-800"><?= $setting->getCompanyName() ?></div>
                                    <!--end::Text-->
                                    <!--end::Description-->
                                    <div class="fw-bold fs-7 text-gray-600"><?= $setting->getCompanyAddress() ?>

                                    </div>
                                    <!--end::Description-->
                                </div>
                                <!--end::Col-->
                            </div>
                            <!--end::Row-->
                            <!--begin::Content-->
                            <div class="flex-grow-1">
                                <!--begin::Table-->
                                <div class="table-responsive border-bottom mb-9">
                                    <table class="table mb-3">
                                        <thead>
                                            <tr class="border-bottom fs-6 fw-bolder text-gray-400">
                                                <th class="min-w-175px pb-2">Description</th>
                                                <!-- <th class="min-w-70px text-end pb-2">Hours</th>
                                                <th class="min-w-80px text-end pb-2">Rate</th> -->
                                                <th class="min-w-100px text-end pb-2">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr class="fw-bolder text-gray-700 fs-5 text-end">
                                                <td class="d-flex align-items-center pt-6">
                                                    <i class="fa fa-genderless text-danger fs-2 me-2"></i><?= $data->getDescription() ?>
                                                </td>
                                                <!--  <td class="pt-6">80</td>
                                                <td class="pt-6">$40.00</td> -->
                                                <td class="pt-6 text-dark fw-boldest">&#8358; <?= $data->getAmount(); ?></td>
                                            </tr>
                                            <!--<tr class="fw-bolder text-gray-700 fs-5 text-end">
                                                <td class="d-flex align-items-center">
                                                    <i class="fa fa-genderless text-success fs-2 me-2"></i>Logo Design
                                                </td>
                                                <td>120</td>
                                                <td>$40.00</td>
                                                <td class="fs-5 text-dark fw-boldest">$4800.00</td>
                                            </tr>
                                            <tr class="fw-bolder text-gray-700 fs-5 text-end">
                                                <td class="d-flex align-items-center">
                                                    <i class="fa fa-genderless text-primary fs-2 me-2"></i>Web Development
                                                </td>
                                                <td>210</td>
                                                <td>$60.00</td>
                                                <td class="fs-5 text-dark fw-boldest">$12600.00</td>
                                            </tr> -->
                                        </tbody>
                                    </table>
                                </div>
                                <!--end::Table-->
                                <!--begin::Container-->
                                <div class="d-flex justify-content-end">
                                    <!--begin::Section-->
                                    <div class="mw-300px">
                                        <!--begin::Item-->
                                        <div class="d-flex flex-stack mb-3">
                                            <!--begin::Accountname-->
                                            <div class="fw-bold pe-10 text-gray-600 fs-7">Subtotal:</div>
                                            <!--end::Accountname-->
                                            <!--begin::Label-->
                                            <div class="text-end fw-bolder fs-6 text-gray-800">&#8358; <?= $data->getAmount() ?></div>
                                            <!--end::Label-->
                                        </div>
                                        <!--end::Item-->
                                        <!--begin::Item-->
                                        <div class="d-flex flex-stack mb-3">
                                            <!--begin::Accountname-->
                                            <div class="fw-bold pe-10 text-gray-600 fs-7">VAT 0%</div>
                                            <!--end::Accountname-->
                                            <!--begin::Label-->
                                            <div class="text-end fw-bolder fs-6 text-gray-800">0.00</div>
                                            <!--end::Label-->
                                        </div>
                                        <!--end::Item-->
                                        <!--begin::Item-->
                                        <div class="d-flex flex-stack mb-3">
                                            <!--begin::Accountnumber-->
                                            <div class="fw-bold pe-10 text-gray-600 fs-7">Subtotal + VAT</div>
                                            <!--end::Accountnumber-->
                                            <!--begin::Number-->
                                            <div class="text-end fw-bolder fs-6 text-gray-800">&#8358; <?= $data->getAmount() ?></div>
                                            <!--end::Number-->
                                        </div>
                                        <!--end::Item-->
                                        <!--begin::Item-->
                                        <div class="d-flex flex-stack">
                                            <!--begin::Code-->
                                            <div class="fw-bold pe-10 text-gray-600 fs-7">Total</div>
                                            <!--end::Code-->
                                            <!--begin::Label-->
                                            <div class="text-end fw-bolder fs-6 text-gray-800">&#8358; <?= $data->getAmount() ?></div>
                                            <!--end::Label-->
                                        </div>
                                        <!--end::Item-->
                                    </div>
                                    <!--end::Section-->


                                </div>
                                <!--end::Container-->
                            </div>
                            <!--end::Content-->
                            <div v-if="hasLoadedInvoiceDets">

                                <!-- <a href="#" class="btn btn-sm btn-success me-2" onclick="window.print()">Print</a> -->
                                <?php if ($data->getStatus()->getId() == TransactionService::INVOICE_STATUS_INITIATED || $data->getStatus()->getId() == TransactionService::INVOICE_STATUS_UNSETTLED) : ?>
                                    <button @click="makePayment()" class="btn btn-lg block btn-primary" type="submit"> Pay </button>
                                <?php endif; ?>

                            </div>
                        </div>
                        <!--end::Wrapper-->
                    </div>
                    <!--end::Content-->
                    <!--begin::Sidebar-->
                    <div class="m-0">
                        <!--begin::Invoice sidebar-->
                        <div class="d-print-none border border-dashed border-gray-300 card-rounded h-lg-100 min-w-md-350px p-9 bg-lighten">
                            <!--begin::Labels-->

                            <!--end::Labels-->
                            <!--begin::Title-->
                            <h6 class="mb-8 fw-boldest text-gray-600 text-hover-primary">PAYMENT DETAILS</h6>
                            <!--end::Title-->
                            <!--begin::Item-->
                            <div class="mb-6">
                                <div class="fw-bold text-gray-600 fs-7">Method:</div>
                                <div class="fw-bolder text-gray-800 fs-6">CARD</div>
                            </div>
                            <!--end::Item-->
                            <!--begin::Item-->
                            <div class="mb-6">
                                <div class="fw-bold text-gray-600 fs-7">Amount Payable:</div>
                                <div class="fw-bolder text-gray-800 fs-6">&#8358; <?= $data->getAmount() ?>

                                </div>
                            </div>
                            <!--end::Item-->
                            <!--begin::Item-->


                        </div>
                        <!--end::Invoice sidebar-->
                    </div>
                    <!--end::Sidebar-->
                </div>
                <!--end::Layout-->
            </div>
            <!--end::Body-->
        </div>
        <!--end::Invoice-->
    </div>
    <!--end::Post-->
</div>




<script>
    const invoiceApp = Vue.createApp({
        data() {
            return {
                // invoiceUid: value,
                paystackKey: "",
                userEmail: "",
                paymentAmount: "",
                invoiceRef: "",
                hasLoadedInvoiceDets: false,
            }
        },

        mounted() {
            this.getInvoiceDetails();
        },

        methods: {



            getInvoiceDetails() {

                setTimeout(() => {
                    // call invoiceSession Action
                    axios.get("/invoice/invoice-session").then(res => {
                        if (res.status == 200) {
                            this.hasLoadedInvoiceDets = true;
                            this.paymentAmount = res.data.data.amount;
                            this.userEmail = res.data.data.email;
                            this.invoiceRef = res.data.data.ref;
                            this.paystackKey = res.data.data.pkey;
                        }
                    }).catch();
                }, 2000);
            },

            getInvoiceSetting() {

            },



            makePayment() {
                // console.log(this.invoiceRef);
                var handler = PaystackPop.setup({
                    key: this.paystackKey, // Replace with your public key
                    email: this.userEmail,
                    amount: this.paymentAmount * 100, // the amount value is multiplied by 100 to convert to the lowest currency unit
                    currency: 'NGN', // Use GHS for Ghana Cedis or USD for US Dollars
                    ref: this.invoiceRef, // Replace with a reference you generated
                    callback: function(response) {
                        // message: "Approved"
                        // redirecturl: "?trxref=T325045183374237&reference=T325045183374237"
                        // reference: "T325045183374237"
                        // status: "success"
                        // trans: "2626859166"
                        // transaction: "2626859166"
                        // trxref: "T325045183374237"

                        if (response.status == "success") {
                            let formData = new FormData();
                            formData.append("ref", response.reference);
                            formData.append("transaction", response.transaction);
                            formData.append("invoice", this.invoiceRef);
                            axios.post("/invoice/verifypayment", formData).then(res => {
                                if (res.status == 201) {
                                    window.location.reload();
                                }
                            }).catch(err => {

                            });
                        }

                        // alert("Got Here");
                        //this happens after the payment is completed successfully
                        // console.log(response);

                        // console.log(response);
                        var reference = response.reference;
                        // alert('Payment complete! Reference: ' + reference);
                        // Make an AJAX call to your server with the reference to verify the transaction
                    },
                    onClose: function() {
                        alert('Transaction was not completed, window closed.');
                    },
                });
                handler.openIframe();
            }


        },
    })
    // invoiceApp.use(VueSwal);
    invoiceApp.use(VueToast.ToastPlugin);

    invoiceApp.mount("#vvInvoice");
</script>