<?php

use Application\Service\GeneralService;

$this->headMeta($description ?? GeneralService::APP_DESCRIPTION, "description");
$this->headMeta($description ?? GeneralService::APP_KEYWORDS, "keywords");
?>
<div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
	<!--begin::Aside-->
	<div id="kt_aside" class="aside card" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_mobile_toggle" data-kt-sticky="true" data-kt-sticky-name="aside-sticky" data-kt-sticky-offset="{default: false, lg: '200px'}" data-kt-sticky-width="{lg: '265px'}" data-kt-sticky-left="auto" data-kt-sticky-top="95px" data-kt-sticky-animation="false" data-kt-sticky-zindex="95">
		<!--begin::Aside menu-->
		<div class="aside-menu flex-column-fluid">
			<!--begin::Aside Menu-->
			<div class="hover-scroll-overlay-y my-5 my-lg-6" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_header, #kt_toolbar, #kt_aside_footer, #kt_footer" data-kt-scroll-wrappers="#kt_aside, #kt_aside_menu" data-kt-scroll-offset="0px">
				<!--begin::Menu-->





				<?php echo $this->partial("partials-rtl-menu") ?>
				<!--end::Menu--> .
			</div>
		</div>
		<!--end::Aside menu-->
		<!--begin::Footer-->

		<!--end::Footer-->
	</div>
	<!--end::Aside-->
	<!--begin::Post-->


	<div class="content flex-row-fluid" id="kt_content">

		<div class="d-flex flex-column flex-xl-row">
			<!--begin::Index-->



			<div class="flex-lg-row-fluid ms-lg-10">
				<div class="card card-page">
					<!--begin::Card body-->
					<div class="card-body">
						<!--begin::Row-->
						<div class="row gy-5 g-xl-8">
							<!--begin::Col-->

							<?= $this->partial("partials-login") ?>

							<div class="col-xxl-4">
								<!--begin::Table Widget 1-->


								<div class="col-xxl-12">

									<!--begin::Title-->
									<h1 class="text-gray-800 fw-bolder mb-4">How to Get a Travel Insurance</h1>
									<!--end::Title-->
									<!--begin::Accordion-->
									<!--begin::Section-->
									<div class="m-0">
										<!--begin::Heading-->
										<div class="d-flex align-items-center collapsible py-3 toggle mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_1">
											<!--begin::Icon-->
											<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
												<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
												<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
												<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
												<span class="svg-icon toggle-off svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
														<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
											</div>
											<!--end::Icon-->
											<!--begin::Title-->
											<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Gather required Documents</h4>
											<!--end::Title-->
										</div>
										<!--end::Heading-->
										<!--begin::Body-->
										<div id="kt_job_4_1" class="collapse show fs-6 ms-1">
											<!--begin::Text-->
											<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">Gather documents which may include,
												Vehicle License, proof of ownership, means of identification, which includes
												but not limited to drivers License, International passport,
												National ID card, front, back side and internal photographs of the vehicle </div>
											<!--end::Text-->
										</div>
										<!--end::Content-->
										<!--begin::Separator-->
										<div class="separator separator-dashed"></div>
										<!--end::Separator-->
									</div>
									<!--end::Section-->
									<!--begin::Section-->
									<div class="m-0">
										<!--begin::Heading-->
										<div class="d-flex align-items-center collapsible py-3 toggle collapsed mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_2">
											<!--begin::Icon-->
											<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
												<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
												<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
												<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
												<span class="svg-icon toggle-off svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
														<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
											</div>
											<!--end::Icon-->
											<!--begin::Title-->
											<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Fill and Upload the required Document</h4>
											<!--end::Title-->
										</div>
										<!--end::Heading-->
										<!--begin::Body-->
										<div id="kt_job_4_2" class="collapse fs-6 ms-1">
											<!--begin::Text-->
											<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">Fill all required fields and upload all required documents</div>
											<!--end::Text-->
										</div>
										<!--end::Content-->
										<!--begin::Separator-->
										<div class="separator separator-dashed"></div>
										<!--end::Separator-->
									</div>
									<!--end::Section-->
									<!--begin::Section-->
									<div class="m-0">
										<!--begin::Heading-->
										<div class="d-flex align-items-center collapsible py-3 toggle collapsed mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_3">
											<!--begin::Icon-->
											<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
												<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
												<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
												<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
												<span class="svg-icon toggle-off svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
														<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
											</div>
											<!--end::Icon-->
											<!--begin::Title-->
											<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Make Payment</h4>
											<!--end::Title-->
										</div>
										<!--end::Heading-->
										<!--begin::Body-->
										<div id="kt_job_4_3" class="collapse fs-6 ms-1">
											<!--begin::Text-->
											<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">Click the continue button to see generate your premium and respective invoice, Make paymentby providing your card details</div>
											<!--end::Text-->
										</div>
										<!--end::Content-->
										<!--begin::Separator-->
										<div class="separator separator-dashed"></div>
										<!--end::Separator-->
									</div>
									<!--end::Section-->
									<!--begin::Section-->
									<div class="m-0">
										<!--begin::Heading-->
										<div class="d-flex align-items-center collapsible py-3 toggle collapsed mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_4">
											<!--begin::Icon-->
											<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
												<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
												<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
												<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
												<span class="svg-icon toggle-off svg-icon-1">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
														<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
														<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
														<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
													</svg>
												</span>
												<!--end::Svg Icon-->
											</div>
											<!--end::Icon-->
											<!--begin::Title-->
											<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Receive Cerificate</h4>
											<!--end::Title-->
										</div>
										<!--end::Heading-->
										<!--begin::Body-->
										<div id="kt_job_4_4" class="collapse fs-6 ms-1">
											<!--begin::Text-->
											<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">Once payment is successfull, an transaction receipt will be issued to you , and our system will begin printing the certificate </div>
											<!--end::Text-->
										</div>
										<!--end::Content-->
									</div>
									<!--end::Section-->
									<!--end::Accordion-->
								</div>


								<!--end::Table Widget 1-->
							</div>

							<div class="col-xxl-8">


								<!--begin::Table Widget 1-->

								<!--begin::Header-->

								<!--end::Header-->
								<!--begin::Body-->

								<div id="travelv" class="card card-page">

									<!--begin::Card body-->
									<div class="card-body">

										<div class="flex-row-fluid py-lg-5 px-lg-15">
											<!--begin::Form-->
											<form autocomplete="off" class="form" novalidate="novalidate" id="kt_modal_create_app_form">
												<fieldset :disabled="sessionDetails == null">
													<!--begin::Step 1-->
													<div class="current" data-kt-stepper-element="content">
														<div class="w-100">



														</div>
													</div>
													<hr>



													<?= $this->partial("partials-form-travel") ?>
													<br>
													<br>
													<!--end::Actions-->
												</fieldset>
											</form>
											<!--end::Form-->
										</div>
										<!--end::Body-->

									</div>
								</div>

								<!--end::Table Widget 1-->









							</div>




							<!--end::Col-->

						</div>

					</div>
					<!--end::Card body-->
				</div>
				<!--end::Index-->
			</div>
		</div>
	</div>
	<!--end::Post-->
</div>
<!--end::Root-->

<script>
	const travelapp = Vue.createApp({
		data() {
			return {
				loginApp: loginAppMount,
				loginAppSession: loginAppMount.sessionDetailsStrigify,
				wel: "come",
				travelVariant: "",
				isLoadedVariant: false,
				loadedVariant: [],
				activeVariantDesc: "",
				activeHeader: "",
				isActiveVariantDesc: false,
				isProcessingTravel: true,
				isGroupList: "No",
				groupListState: false,
				travelList: null,
				isSendingTravelData: false,
				travelListSex: [],
				travelCountry: [],
				travelNationality: [],
				travelDestination: [],
				isValidtravelForm: false,
				isSessionAvailable: false,
				loginStata: false,
				minReturnDate: "",

				sessionUid: null,
				sessionDetails: null,
				sessionDetailsStrigify: null,

				isFaniliazedLoginFetch: false,
			}
		},
		mounted() {
			this.getTravelVariant();
			this.getSex();
			this.getCountry();
			// this.setSessionCondition()
			this.getSession();
		},

		// watch: {
		// 	loginAppSession(newValue, oldValue) {
		// 		this.loginState = newValue == "{}" ? true : false;
		// 	}
		// },

		computed: {
			loginStatus() {
				if (this.sessionDetailsStrigify !== null) {

					this.isSessionAvailable = true;
					return true;
				} else {
					this.isSessionAvailable = false;
					return false


				}
			}
		},



		methods: {

			// setSessionCondition(){
			// 	if(){
			// 		console.log(loginAppMount.sessionDetailsStrigify);
			// 		this.isSessionAvailable = true;
			// 	}else{
			// 		this.isSessionAvailable = false;
			// 		// console.log(loginApp.$data.sessionDetailsStrigify);

			// 	}
			// },

			onSelectDetartureDate(e) {
				this.minReturnDate = e.target.value;
			},

			getSession() {
				axios.get("/auth/session").then(res => {
					if (res.status == 200) {
						this.isFaniliazedLoginFetch = true;
						this.sessionDetails = res.data.data;
						this.sessionDetailsStrigify = JSON.stringify(res.data.data);
						// console.log(this.sessionDetailsStrigify);
					}
				}).catch();
			},

			notifcation() {
				alert("Welcom");
			},

			toggleGroupList() {
				this.groupListState = !this.groupListState;
				if (this.groupListState) {
					this.isGroupList = "Yes";
				} else {
					this.isGroupList = "No";
				}
			},
			getSex() {
				axios.get("/app/getsex").then(res => {
					if (res.status == 200) {
						this.travelListSex = res.data.data;
					}
				}).catch();
			},
			getCountry() {
				axios.get("/app/get-country").then(res => {
					if (res.status == 200) {
						this.travelCountry = res.data.data;
						this.travelNationality = res.data.data;
						this.travelDestination = res.data.data;
					}
				}).catch();
			},
			getTravelVariant() {
				this.isLoadedVariant = false;
				axios.get("/travel/get-variant").then(res => {
					if (res.status == 200) {
						this.loadedVariant = res.data.data;
						this.isLoadedVariant = true;
					}
				}).catch(err => {

				})
			},

			getVariantDescription(e) {
				// alert("Hey");
				let tar = e.target.value;
				axios.get("/travel/get-variant-description/" + tar).then(res => {
					if (res.status == 200) {
						this.activeVariantDesc = res.data.data;
						this.activeHeader = res.data.head;
						this.isActiveVariantDesc = true;
					}
				})
			},

			// List functionality

			addToList() {
				if (this.$refs.listSurname.value == "" || this.$refs.listFirstname.value == "" || this.$refs.listDob.value == "") {

					this.$toast.open({
						message: "One of the fields required is empty please fill before adding",
						type: "error",
						position: "top-right",
						duration: 30000,
						dismissible: true
					});

				} else {
					let newObject = {
						surname: this.$refs.listSurname.value,
						lastname: this.$refs.listFirstname.value,
						dob: this.$refs.listDob.value,
						passport: this.$refs.listPassport.value,
						sex: this.$refs.listSex.value,
					};

					this.$refs.listFirstname.value = "";
					this.$refs.listSurname.value = "";
					this.travelList.push(newObject);
				}

			},

			removeFromList(inn) {
				this.travelList.splice(inn, 1);
			},


			variantAction(e) {
				//this.activeVariantDesc = e.target.
				console.log(e.target.value);
			},
			validateTravelForm() {
				if (this.$refs.vDeparture.value == "" || this.$refs.vDob.value == "" || this.$refs.vReturnDate.value == "" || this.$refs.selectedNationality.value == "" || this.$refs.selectedDestination.value == "") {
					this.isValidtravelForm = false;
				} else {
					this.isValidtravelForm = true;
				}
			},
			sendTravel() {
				this.isSendingTravelData = true;
				this.validateTravelForm();
				if (!this.isValidtravelForm) {

					this.$toast.open({
						message: "One of the required field is empty",
						type: "error",
						position: "top-right",
						duration: 30000,
						dismissible: true
					});
					this.isSendingTravelData = false;

				} else {
					this.isSendingTravelData = true;
					let formData = new FormData();
					formData.append("user", this.sessionDetails.uid);
					formData.append("dob", this.$refs.vDob.value);
					formData.append("departureDate", this.$refs.vDeparture.value);
					formData.append("returnDate", this.$refs.vReturnDate.value);
					formData.append("nationality", this.$refs.selectedNationality.value);
					formData.append("destination", this.$refs.selectedDestination.value);
					formData.append("travelList", JSON.stringify(this.travelList));

					// if (this.$refs.passportBio.file[0]) {
					// 	let biopassport = this.$refs.passportBio.file[0];
					// 	if (biopassport.size > 1024 * 1024 * 2) {
					// 		this.$toast.open({
					// 			message: "One of the required field is empty",
					// 			type: "error",
					// 			position: "top-right",
					// 			duration: 30000,
					// 			dismissible: true
					// 		});
					// 		return;
					// 	}
					// }
					// formData.append("departureDate", this.$refs.vDeparture.value);
					axios.post("/travel/intiate", formData).then(res => {
						if (res.status == 201) {
							$responseData = res.data.data;
							window.location.href = "/app/invoice/" + $responseData.invoice.uuid;
							this.isSendingTravelData = false;
						} else {
							this.$toast.open({
								message: res.data.messages,
								type: "error",
								position: "top-right",
								duration: 30000,
								dismissible: true
							});
							this.isSendingTravelData = false;
						}
					}).catch(err => {
						this.$toast.open({
							message: err.response.data.messages,
							type: "error",
							position: "top-right",
							duration: 30000,
							dismissible: true
						});
						this.isSendingTravelData = false;
					});
					// this.isSendingTravelData = false;
				}

			}
		},
	});
	travelapp.use(VueToast.ToastPlugin);
	travelapp.mount("#travelv");
</script>