<div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
	<!--begin::Aside-->
	<div id="kt_aside" class="aside card" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_mobile_toggle" data-kt-sticky="true" data-kt-sticky-name="aside-sticky" data-kt-sticky-offset="{default: false, lg: '200px'}" data-kt-sticky-width="{lg: '265px'}" data-kt-sticky-left="auto" data-kt-sticky-top="95px" data-kt-sticky-animation="false" data-kt-sticky-zindex="95">
		<!--begin::Aside menu-->
		<div class="aside-menu flex-column-fluid">
			<!--begin::Aside Menu-->
			<div class="hover-scroll-overlay-y my-5 my-lg-6" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_header, #kt_toolbar, #kt_aside_footer, #kt_footer" data-kt-scroll-wrappers="#kt_aside, #kt_aside_menu" data-kt-scroll-offset="0px">
				<!--begin::Menu-->





				<?php echo $this->partial("partials-rtl-menu") ?>
				<!--end::Menu--> .
			</div>
		</div>
		<!--end::Aside menu-->
		<!--begin::Footer-->

		<!--end::Footer-->
	</div>
	<!--end::Aside-->
	<!--begin::Post-->
	<div class="content flex-row-fluid" id="kt_content">
		<!--begin::Index-->
		<div class="card card-page">
			<!--begin::Card body-->
			<div class="card-body">
				<!--begin::Row-->
				<div class="row gy-5 g-xl-8">
					<!--begin::Col-->

					<div class="col-xxl-4">
						<!--begin::Table Widget 1-->


						<div class="col-xxl-12">

							<!--begin::Title-->
							<h1 class="text-gray-800 fw-bolder mb-4">How to Get a Travel Insurance</h1>
							<!--end::Title-->
							<!--begin::Accordion-->
							<!--begin::Section-->
							<div class="m-0">
								<!--begin::Heading-->
								<div class="d-flex align-items-center collapsible py-3 toggle mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_1">
									<!--begin::Icon-->
									<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
										<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
										<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
										<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
										<span class="svg-icon toggle-off svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
												<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
									</div>
									<!--end::Icon-->
									<!--begin::Title-->
									<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Gather required Documents</h4>
									<!--end::Title-->
								</div>
								<!--end::Heading-->
								<!--begin::Body-->
								<div id="kt_job_4_1" class="collapse show fs-6 ms-1">
									<!--begin::Text-->
									<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">Gather documents which may include,
										Vehicle License, proof of ownership, means of identification, which includes
										but not limited to drivers License, International passport,
										National ID card, front, back side and internal photographs of the vehicle </div>
									<!--end::Text-->
								</div>
								<!--end::Content-->
								<!--begin::Separator-->
								<div class="separator separator-dashed"></div>
								<!--end::Separator-->
							</div>
							<!--end::Section-->
							<!--begin::Section-->
							<div class="m-0">
								<!--begin::Heading-->
								<div class="d-flex align-items-center collapsible py-3 toggle collapsed mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_2">
									<!--begin::Icon-->
									<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
										<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
										<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
										<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
										<span class="svg-icon toggle-off svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
												<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
									</div>
									<!--end::Icon-->
									<!--begin::Title-->
									<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Fill and Upload the required Document</h4>
									<!--end::Title-->
								</div>
								<!--end::Heading-->
								<!--begin::Body-->
								<div id="kt_job_4_2" class="collapse fs-6 ms-1">
									<!--begin::Text-->
									<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">First, a disclaimer – the entire process of writing a blog post often takes more than a couple of hours, even if you can type eighty words as per minute and your writing skills are sharp.</div>
									<!--end::Text-->
								</div>
								<!--end::Content-->
								<!--begin::Separator-->
								<div class="separator separator-dashed"></div>
								<!--end::Separator-->
							</div>
							<!--end::Section-->
							<!--begin::Section-->
							<div class="m-0">
								<!--begin::Heading-->
								<div class="d-flex align-items-center collapsible py-3 toggle collapsed mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_3">
									<!--begin::Icon-->
									<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
										<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
										<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
										<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
										<span class="svg-icon toggle-off svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
												<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
									</div>
									<!--end::Icon-->
									<!--begin::Title-->
									<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Make Payment</h4>
									<!--end::Title-->
								</div>
								<!--end::Heading-->
								<!--begin::Body-->
								<div id="kt_job_4_3" class="collapse fs-6 ms-1">
									<!--begin::Text-->
									<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">First, a disclaimer – the entire process of writing a blog post often takes more than a couple of hours, even if you can type eighty words as per minute and your writing skills are sharp.</div>
									<!--end::Text-->
								</div>
								<!--end::Content-->
								<!--begin::Separator-->
								<div class="separator separator-dashed"></div>
								<!--end::Separator-->
							</div>
							<!--end::Section-->
							<!--begin::Section-->
							<div class="m-0">
								<!--begin::Heading-->
								<div class="d-flex align-items-center collapsible py-3 toggle collapsed mb-0" data-bs-toggle="collapse" data-bs-target="#kt_job_4_4">
									<!--begin::Icon-->
									<div class="btn btn-sm btn-icon mw-20px btn-active-color-primary me-5">
										<!--begin::Svg Icon | path: icons/duotune/general/gen036.svg-->
										<span class="svg-icon toggle-on svg-icon-primary svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="6.0104" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
										<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
										<span class="svg-icon toggle-off svg-icon-1">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
												<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
												<rect x="10.8891" y="17.8033" width="12" height="2" rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
												<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
											</svg>
										</span>
										<!--end::Svg Icon-->
									</div>
									<!--end::Icon-->
									<!--begin::Title-->
									<h4 class="text-gray-700 fw-bolder cursor-pointer mb-0">Receive Cerificate</h4>
									<!--end::Title-->
								</div>
								<!--end::Heading-->
								<!--begin::Body-->
								<div id="kt_job_4_4" class="collapse fs-6 ms-1">
									<!--begin::Text-->
									<div class="mb-4 text-gray-600 fw-bold fs-6 ps-10">First, a disclaimer – the entire process of writing a blog post often takes more than a couple of hours, even if you can type eighty words as per minute and your writing skills are sharp.</div>
									<!--end::Text-->
								</div>
								<!--end::Content-->
							</div>
							<!--end::Section-->
							<!--end::Accordion-->
						</div>


						<!--end::Table Widget 1-->
					</div>

					<div class="col-xxl-8">




						<!--begin::Table Widget 1-->

						<!--begin::Header-->

						<!--end::Header-->
						<!--begin::Body-->

						<div id="travelv" class="card card-page">

							<!--begin::Card body-->
							<div class="card-body">

								<div class="flex-row-fluid py-lg-5 px-lg-15">
									<!--begin::Form-->
									<form class="form" novalidate="novalidate" id="kt_modal_create_app_form">
										<!--begin::Step 1-->
										<div class="current" data-kt-stepper-element="content">
											<div class="w-100">

												
												
											</div>
										</div>
										<hr>



										<?= $this->partial("partials-form-travel") ?>
										<br>
										<br>
										<!--end::Actions-->
									</form>
									<!--end::Form-->
								</div>
								<!--end::Body-->

							</div>
						</div>

						<!--end::Table Widget 1-->









					</div>




					<!--end::Col-->

				</div>

			</div>
			<!--end::Card body-->
		</div>
		<!--end::Index-->
	</div>
	<!--end::Post-->
</div>
<!--end::Root-->

<script>
	const travelapp = Vue.createApp({
		data() {
			return {
				wel: "come",
				travelVariant: "",
				isLoadedVariant: false,
				loadedVariant: [],
				activeVariantDesc: "",
				activeHeader:"",
				isActiveVariantDesc:false,
				isProcessingTravel: true,
				isGroupList:"No",
				groupListState:false,
			}
		},
		mounted() {
			this.getTravelVariant();
		},

		

		methods: {

			toggleGroupList(){
				this.groupListState = !this.groupListState;
				if(this.groupListState){
					this.isGroupList = "Yes";
				}else{
					this.isGroupList = "No";
				}
			},
			getTravelVariant() {
				this.isLoadedVariant = false;
				axios.get("/travel/get-variant").then(res => {
					if (res.status == 200) {
						this.loadedVariant = res.data.data;
						this.isLoadedVariant = true;
					}
				}).catch(err => {

				})
			},

			getVariantDescription(e){
				let tar = e.target.value;
				axios.get("/travel/get-variant-description/"+tar).then(res=>{
					if(res.status == 200){
						this.activeVariantDesc = res.data.data;
						this.activeHeader = res.data.head;
						this.isActiveVariantDesc = true;
					}
				})
			},


			variantAction(e){
				//this.activeVariantDesc = e.target.
				console.log(e.target.value);
			},
			sendTravel() {

			}
		},
	});
	travelapp.use(VueToast.ToastPlugin);
	travelapp.mount("#travelv");
</script>